### ISSUE TITLE
BAD APP

### ISSUE THREAD

**Issue by markalmax** [FeloNashaat/YTH264#1]
bro I can't even download in 144p why would I use that app and not use any other app 
ADD
OPTIONS 
FOR 
144P

and thank you 
-markalmax :>

**Comment by CopticFelo** [comment]
Q: Why there is no 144p?
A: It's not important for me so I don't care + 144p exists but only if the video quality is low enough

Q: Why would you use this app instead of other apps?
A: 
The other apps have ads + Not open source
If you don't think this a good reason to use it then
Nobody said you should
I am just practicing making apps with Flutter so even if it doesn't have any competitive advantages, that's not the point of it

**Comment by markalmax** [comment]
KYS
